server:
  port: 9990
spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://rm-wz963ju312wgv19502o.mysql.rds.aliyuncs.com:3306/zeus_finance?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
      username: mozi_root
      password: Cd40k1SKIXBQ
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  // 通过全局配置，设置实体类所对应表的统一前缀
#  global-config:
#    db-config:
#      table-prefix: t_
